server:
  port: 8080
  error:
    include-message: always

spring:
  graphql:
    graphiql:
      enabled: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/poi
    username: root
    password: wcl20031030
    driver-class-name: com.mysql.cj.jdbc.Driver
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: wcl20031030
  kafka:
    bootstrap-servers: localhost:9092  # Kafka服务器地址，根据实际配置更改
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      properties:
        spring.json.trusted.packages: "*"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: order-processing-group
      auto-offset-reset: earliest
  data:
    redis:
      host: localhost
      port: 6379
      password:
    mongodb:
      uri: mongodb://localhost:27017/samples
eureka:
  instance:
    prefer-ip-address: true
    ip-address: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8040/eureka




upload:
  localPath: D:\home/
  accessPath: /upload/
